name: CI

on:
  push:
    branches: [ master, 'feature/*' ]
  pull_request:
    branches: [ master, 'feature/*' ]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies (client)
        run: |
          cd client
          npm install
      - name: Install dependencies (server)
        run: |
          cd server
          npm install

  run-tests:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run client tests (Vitest)
        run: |
          cd client
          npm test
      - name: Run server tests (Jest)
        run: |
          cd server
          npm test

  build-frontend:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build client
        run: |
          cd client
          npm run build 